### ISSUE TITLE
Como administrador de Pulpín quiero poder gestionar los eventos que utilicemos en la aplicación

### ISSUE THREAD

**Issue by christianpe98** [christianpe98/pulpin-server#18]
- [ ] https://github.com/DistributedPixels/pulpin-server/issues/15
- [ ] https://github.com/DistributedPixels/pulpin-client/issues/10
- [ ] https://github.com/DistributedPixels/pulpin-server/issues/17
- [ ] https://github.com/DistributedPixels/pulpin-client/issues/12
- [ ] https://github.com/DistributedPixels/pulpin-server/issues/24
