### ISSUE TITLE
Como usuario de pulpín quiero poder crear alertas para los eventos que me interesen

### ISSUE THREAD

**Issue by christianpe98** [christianpe98/pulpin-server#19]
- [ ] https://github.com/DistributedPixels/pulpin-server/issues/14
- [ ] https://github.com/DistributedPixels/pulpin-server/issues/16
- [ ] https://github.com/DistributedPixels/pulpin-client/issues/11
- [ ] https://github.com/DistributedPixels/pulpin-server/issues/20
- [ ] https://github.com/DistributedPixels/pulpin-server/issues/21
- [ ] https://github.com/DistributedPixels/pulpin-client/issues/13
